/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author susha
 */
package Restaurant_Bill;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.time;
import java.awt.Component;
import javax.swing.*;
import java.awt.TextField;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.UnsupportedLookAndFeelException;


public class Restaurant_Bill extends javax.swing.JFrame {

    /**
     * Creates new form Restaurant_Bill
     */
    public Restaurant_Bill() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanelMeals = new javax.swing.JPanel();
        jTax1 = new javax.swing.JLabel();
        jSubTotal1 = new javax.swing.JLabel();
        jTotal1 = new javax.swing.JLabel();
        jTextVegBurger = new javax.swing.JTextField();
        jTextPaneerBurger = new javax.swing.JTextField();
        jTextChowmean = new javax.swing.JTextField();
        jTax2 = new javax.swing.JLabel();
        jTotal2 = new javax.swing.JLabel();
        jTextPaasta = new javax.swing.JTextField();
        jTextSnacks = new javax.swing.JTextField();
        jTextParatha = new javax.swing.JTextField();
        jTextPizza = new javax.swing.JTextField();
        jTotal3 = new javax.swing.JLabel();
        jTotal4 = new javax.swing.JLabel();
        jTotal5 = new javax.swing.JLabel();
        jPanelTotal = new javax.swing.JPanel();
        jTextTax = new javax.swing.JTextField();
        jTextSubTotal = new javax.swing.JTextField();
        jTextTotal = new javax.swing.JTextField();
        jTax = new javax.swing.JLabel();
        jSubTotal = new javax.swing.JLabel();
        jTotal = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jButttonTotal = new javax.swing.JButton();
        jButtonReceipt = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextReceipt = new javax.swing.JTextArea();
        jPanelDrinks = new javax.swing.JPanel();
        jTax3 = new javax.swing.JLabel();
        jSubTotal2 = new javax.swing.JLabel();
        jTotal6 = new javax.swing.JLabel();
        jTextVanilla = new javax.swing.JTextField();
        jTextMango = new javax.swing.JTextField();
        jTextOreo = new javax.swing.JTextField();
        jTax4 = new javax.swing.JLabel();
        jTotal7 = new javax.swing.JLabel();
        jTextBanana = new javax.swing.JTextField();
        jTextChoclate = new javax.swing.JTextField();
        jTextLassi = new javax.swing.JTextField();
        jTextCold = new javax.swing.JTextField();
        jTotal8 = new javax.swing.JLabel();
        jTotal9 = new javax.swing.JLabel();
        jTotal10 = new javax.swing.JLabel();
        jPanelCost = new javax.swing.JPanel();
        jTextCostMeal = new javax.swing.JTextField();
        jTextCostDrink = new javax.swing.JTextField();
        jTextTotalCost = new javax.swing.JTextField();
        jTax5 = new javax.swing.JLabel();
        jSubTotal3 = new javax.swing.JLabel();
        jTotal11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Restaurant Bill System");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 55)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Agarwal's Restaurant");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\susha\\Desktop\\restaurant.jpg")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(47, 47, 47))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 120));

        jPanelMeals.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));

        jTax1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTax1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTax1.setText("Veg - Burger");

        jSubTotal1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jSubTotal1.setText("Paneer - Burger");

        jTotal1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTotal1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTotal1.setText("Chowmean");
        jTotal1.setToolTipText("");

        jTextVegBurger.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextVegBurger.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextVegBurger.setText("0");
        jTextVegBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextVegBurgerActionPerformed(evt);
            }
        });

        jTextPaneerBurger.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextPaneerBurger.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextPaneerBurger.setText("0");
        jTextPaneerBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPaneerBurgerActionPerformed(evt);
            }
        });

        jTextChowmean.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextChowmean.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextChowmean.setText("0");
        jTextChowmean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextChowmeanActionPerformed(evt);
            }
        });

        jTax2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jTax2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTax2.setText("MEAL");

        jTotal2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTotal2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTotal2.setText("Paasta");
        jTotal2.setToolTipText("");

        jTextPaasta.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextPaasta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextPaasta.setText("0");
        jTextPaasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPaastaActionPerformed(evt);
            }
        });

        jTextSnacks.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextSnacks.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextSnacks.setText("0");
        jTextSnacks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextSnacksActionPerformed(evt);
            }
        });

        jTextParatha.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextParatha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextParatha.setText("0");
        jTextParatha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextParathaActionPerformed(evt);
            }
        });

        jTextPizza.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextPizza.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextPizza.setText("0");
        jTextPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPizzaActionPerformed(evt);
            }
        });

        jTotal3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTotal3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTotal3.setText("Snacks");
        jTotal3.setToolTipText("");

        jTotal4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTotal4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTotal4.setText("Paratha");
        jTotal4.setToolTipText("");

        jTotal5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTotal5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTotal5.setText("Pizza");
        jTotal5.setToolTipText("");

        javax.swing.GroupLayout jPanelMealsLayout = new javax.swing.GroupLayout(jPanelMeals);
        jPanelMeals.setLayout(jPanelMealsLayout);
        jPanelMealsLayout.setHorizontalGroup(
            jPanelMealsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMealsLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jTax2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
            .addGroup(jPanelMealsLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanelMealsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTotal2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSubTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTax1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTotal3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTotal4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTotal5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelMealsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextChowmean, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(jTextPaneerBurger, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextVegBurger, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextPaasta)
                    .addComponent(jTextSnacks, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextParatha, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextPizza, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(31, 31, 31))
        );
        jPanelMealsLayout.setVerticalGroup(
            jPanelMealsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMealsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMealsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMealsLayout.createSequentialGroup()
                        .addComponent(jTax2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanelMealsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTax1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextVegBurger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelMealsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSubTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextPaneerBurger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelMealsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextChowmean, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelMealsLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jTotal1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelMealsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTotal2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextPaasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextSnacks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelMealsLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jTotal3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMealsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextParatha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTotal4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMealsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextPizza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTotal5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        getContentPane().add(jPanelMeals, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 300, 280));

        jPanelTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));

        jTextTax.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTaxActionPerformed(evt);
            }
        });

        jTextSubTotal.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextSubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextSubTotalActionPerformed(evt);
            }
        });

        jTextTotal.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTotalActionPerformed(evt);
            }
        });

        jTax.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTax.setText("TAX :");

        jSubTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jSubTotal.setText("Sub-Total");

        jTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTotal.setText("Total :");

        javax.swing.GroupLayout jPanelTotalLayout = new javax.swing.GroupLayout(jPanelTotal);
        jPanelTotal.setLayout(jPanelTotalLayout);
        jPanelTotalLayout.setHorizontalGroup(
            jPanelTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTotalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTax, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(jPanelTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextTax, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
        jPanelTotalLayout.setVerticalGroup(
            jPanelTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTotalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextTax))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanelTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelTotalLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, 300, 120));

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));

        jButttonTotal.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButttonTotal.setText("Total");
        jButttonTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButttonTotalActionPerformed(evt);
            }
        });

        jButtonReceipt.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButtonReceipt.setText("Receipt");
        jButtonReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReceiptActionPerformed(evt);
            }
        });

        jButtonReset.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButtonReset.setText("Reset");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        jButtonExit.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jButttonTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jButtonReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButttonTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 610, 90));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));

        jTextReceipt.setColumns(20);
        jTextReceipt.setRows(5);
        jScrollPane1.setViewportView(jTextReceipt);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 130, 360, 510));

        jPanelDrinks.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));

        jTax3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTax3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTax3.setText("Vanilla-Shake");

        jSubTotal2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jSubTotal2.setText("Mango-Shake");

        jTotal6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTotal6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTotal6.setText("Oreo-Shake");
        jTotal6.setToolTipText("");

        jTextVanilla.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextVanilla.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextVanilla.setText("0");
        jTextVanilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextVanillaActionPerformed(evt);
            }
        });

        jTextMango.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextMango.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextMango.setText("0");
        jTextMango.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextMangoActionPerformed(evt);
            }
        });

        jTextOreo.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextOreo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextOreo.setText("0");
        jTextOreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextOreoActionPerformed(evt);
            }
        });

        jTax4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jTax4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTax4.setText("DRINKS");

        jTotal7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTotal7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTotal7.setText("Banana-Shake");
        jTotal7.setToolTipText("");

        jTextBanana.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextBanana.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextBanana.setText("0");
        jTextBanana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextBananaActionPerformed(evt);
            }
        });

        jTextChoclate.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextChoclate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextChoclate.setText("0");
        jTextChoclate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextChoclateActionPerformed(evt);
            }
        });

        jTextLassi.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextLassi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextLassi.setText("0");
        jTextLassi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextLassiActionPerformed(evt);
            }
        });

        jTextCold.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextCold.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextCold.setText("0");
        jTextCold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextColdActionPerformed(evt);
            }
        });

        jTotal8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTotal8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTotal8.setText("Choclate-Shake");
        jTotal8.setToolTipText("");

        jTotal9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTotal9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTotal9.setText("Lassi");
        jTotal9.setToolTipText("");

        jTotal10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTotal10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jTotal10.setText("Cold-Drink");
        jTotal10.setToolTipText("");

        javax.swing.GroupLayout jPanelDrinksLayout = new javax.swing.GroupLayout(jPanelDrinks);
        jPanelDrinks.setLayout(jPanelDrinksLayout);
        jPanelDrinksLayout.setHorizontalGroup(
            jPanelDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDrinksLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jTax4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
            .addGroup(jPanelDrinksLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanelDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTotal7, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTotal6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSubTotal2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTax3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTotal8, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTotal9, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTotal10, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextOreo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(jTextMango, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextVanilla, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextBanana)
                    .addComponent(jTextChoclate, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextLassi, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextCold, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(31, 31, 31))
        );
        jPanelDrinksLayout.setVerticalGroup(
            jPanelDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDrinksLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDrinksLayout.createSequentialGroup()
                        .addComponent(jTax4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanelDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTax3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextVanilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSubTotal2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextMango, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextOreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelDrinksLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jTotal6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTotal7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextBanana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextChoclate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDrinksLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jTotal8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextLassi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTotal9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextCold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTotal10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        getContentPane().add(jPanelDrinks, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, -1, 280));

        jPanelCost.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));

        jTextCostMeal.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextCostMeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCostMealActionPerformed(evt);
            }
        });

        jTextCostDrink.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextCostDrink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCostDrinkActionPerformed(evt);
            }
        });

        jTextTotalCost.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextTotalCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTotalCostActionPerformed(evt);
            }
        });

        jTax5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTax5.setText("Cost of Meal");

        jSubTotal3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jSubTotal3.setText("Cost of Drink");

        jTotal11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTotal11.setText("Total Cost of Item");

        javax.swing.GroupLayout jPanelCostLayout = new javax.swing.GroupLayout(jPanelCost);
        jPanelCost.setLayout(jPanelCostLayout);
        jPanelCostLayout.setHorizontalGroup(
            jPanelCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCostLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTax5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSubTotal3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTotal11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanelCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextTotalCost, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextCostDrink, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextCostMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
        jPanelCostLayout.setVerticalGroup(
            jPanelCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCostLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTax5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextCostMeal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextCostDrink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSubTotal3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanelCostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextTotalCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelCostLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jTotal11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

   
    
    private void jButttonTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButttonTotalActionPerformed
        // TODO add your handling code here:
        SubClass ItemCost = new SubClass();
        
        ItemCost.VegBurger = ItemCost.pVegBurger * Double.parseDouble(jTextVegBurger.getText());
        ItemCost.PaneerBurger = ItemCost.pPaneerBurger * Double.parseDouble(jTextPaneerBurger.getText());
        ItemCost.Chowmean = ItemCost.pChowmean * Double.parseDouble(jTextChowmean.getText());
        ItemCost.Paasta = ItemCost.pPaasta * Double.parseDouble(jTextPaasta.getText());
        ItemCost.Pizza = ItemCost.pPizza * Double.parseDouble(jTextPizza.getText());
        ItemCost.Paratha = ItemCost.pParatha * Double.parseDouble(jTextParatha.getText());
        ItemCost.Snacks = ItemCost.pSnacks * Double.parseDouble(jTextSnacks.getText());
        
        ItemCost.VanillaShake = ItemCost.pVanillaShake * Double.parseDouble(jTextVanilla.getText());
        ItemCost.MangoShake = ItemCost.pMangoShake * Double.parseDouble(jTextMango.getText());
        ItemCost.BananaShake = ItemCost.pBananaShake * Double.parseDouble(jTextBanana.getText());
        ItemCost.OreoShake = ItemCost.pOreoShake * Double.parseDouble(jTextOreo.getText());
        ItemCost.Lassi = ItemCost.pLassi * Double.parseDouble(jTextLassi.getText());
        ItemCost.ColdDrink = ItemCost.pColdDrink * Double.parseDouble(jTextCold.getText());
        ItemCost.ChoclateShake = ItemCost.pChoclateShake * Double.parseDouble(jTextChoclate.getText());
        
        double iSubTotal = ItemCost.getAmount();
        double iTax = ItemCost.cFindTax(iSubTotal);
        double iTotal = iSubTotal + iTax;
        
        String SubTotal = String.format("₹%.2f", iSubTotal);
        jTextSubTotal.setText(SubTotal);
        
        String Tax = String.format("₹%.2f", iTax);
        jTextTax.setText(Tax);
        
        String Total = String.format("₹%.2f", iTotal);
        jTextTotal.setText(Total);
        
        String Meal = String.format("₹%.2f", ItemCost.Meals);
        jTextCostMeal.setText(Meal);
        
        String Drink = String.format("₹%.2f", ItemCost.Drinks);
        jTextCostDrink.setText(Drink);
        
        String TotalItem = String.format("₹%.2f", ItemCost.TotalofMade);
        jTextTotalCost.setText(TotalItem);
       
        
    }//GEN-LAST:event_jButttonTotalActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
     SubClass iExit = new  SubClass();
     iExit.iExitSystem();
        
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jTextTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTaxActionPerformed

    private void jTextSubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextSubTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextSubTotalActionPerformed

    private void jTextTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTotalActionPerformed

    private void jTextPaneerBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPaneerBurgerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPaneerBurgerActionPerformed

    private void jTextChowmeanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextChowmeanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextChowmeanActionPerformed

    private void jTextVegBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextVegBurgerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextVegBurgerActionPerformed

    private void jTextPaastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPaastaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPaastaActionPerformed

    private void jTextSnacksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextSnacksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextSnacksActionPerformed

    private void jTextParathaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextParathaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextParathaActionPerformed

    private void jTextPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPizzaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPizzaActionPerformed

    private void jTextVanillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextVanillaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextVanillaActionPerformed

    private void jTextMangoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextMangoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextMangoActionPerformed

    private void jTextOreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextOreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextOreoActionPerformed

    private void jTextBananaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextBananaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextBananaActionPerformed

    private void jTextChoclateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextChoclateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextChoclateActionPerformed

    private void jTextLassiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextLassiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextLassiActionPerformed

    private void jTextColdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextColdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextColdActionPerformed

    private void jTextCostMealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCostMealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCostMealActionPerformed

    private void jTextCostDrinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCostDrinkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCostDrinkActionPerformed

    private void jTextTotalCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTotalCostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTotalCostActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        // TODO add your handling code here:
        jTextVegBurger.setText("0");
        jTextPaneerBurger.setText("0");
        jTextChowmean.setText("0");
        jTextPaasta.setText("0");
        jTextSnacks.setText("0");
        jTextParatha.setText("0");
        jTextPizza.setText("0");
        
        jTextVanilla.setText("0");
        jTextMango.setText("0");
        jTextOreo.setText("0");
        jTextBanana.setText("0");
        jTextChoclate.setText("0");
        jTextLassi.setText("0");
        jTextCold.setText("0");
        
        jTextCostMeal.setText(null);
        jTextCostDrink.setText(null);
        jTextTotalCost.setText(null);
        
        jTextTax.setText(null);
        jTextSubTotal.setText(null);
        jTextTotal.setText(null);
        
        jTextReceipt.setText(null);
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jButtonReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReceiptActionPerformed
        // TODO add your handling code here:
        
        //========================================
        int refs = 1325 + (int) (Math.random()*4238);
        
        Calendar timer = Calendar.getInstance();
        timer.getTime();
        SimpleDateFormat tTime = new SimpleDateFormat("HH:mm:ss");
        tTime.format(timer.getTime());
        SimpleDateFormat tDate = new SimpleDateFormat("dd-MM-YYYY");
        tDate.format(timer.getTime());
        
        
        
        jTextReceipt.append("\tAgrawal's Restaurant Bill:\n" + 
                        "\n  Reference: \t\t" + refs + 
                "\n========================================\n" + 
                "\n  Meals:\t\t" + jTextCostMeal.getText() + "\n\n" + 
                "\n  Drinks:\t\t" + jTextCostDrink.getText() + "\n\n" +
                "\n  Cost of Items:\t\t" + jTextTotalCost.getText() + "\n" +
                "\n========================================\n" +
                "\n  Tax:\t\t" + jTextTax.getText() + "\n\n" + 
                "\n  SubTotal:\t\t" + jTextSubTotal.getText() + "\n\n" +
                "\n  Total:\t\t" + jTextTotal.getText() + "\n" +
                "\n========================================\n" +
                
                "  Date:\t" + tDate.format(timer.getTime()) + 
                "\n\n  Time:\t" + tTime.format(timer.getTime()) +
                "\n\n\t\tThank You!!"
      
        );  
        
        
    }//GEN-LAST:event_jButtonReceiptActionPerformed

    /**
     * @param args the command line arguments
     * @throws java.lang.ClassNotFoundException
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Restaurant_Bill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonReceipt;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JButton jButttonTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanelCost;
    private javax.swing.JPanel jPanelDrinks;
    private javax.swing.JPanel jPanelMeals;
    private javax.swing.JPanel jPanelTotal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jSubTotal;
    private javax.swing.JLabel jSubTotal1;
    private javax.swing.JLabel jSubTotal2;
    private javax.swing.JLabel jSubTotal3;
    private javax.swing.JLabel jTax;
    private javax.swing.JLabel jTax1;
    private javax.swing.JLabel jTax2;
    private javax.swing.JLabel jTax3;
    private javax.swing.JLabel jTax4;
    private javax.swing.JLabel jTax5;
    private javax.swing.JTextField jTextBanana;
    private javax.swing.JTextField jTextChoclate;
    private javax.swing.JTextField jTextChowmean;
    private javax.swing.JTextField jTextCold;
    private javax.swing.JTextField jTextCostDrink;
    private javax.swing.JTextField jTextCostMeal;
    private javax.swing.JTextField jTextLassi;
    private javax.swing.JTextField jTextMango;
    private javax.swing.JTextField jTextOreo;
    private javax.swing.JTextField jTextPaasta;
    private javax.swing.JTextField jTextPaneerBurger;
    private javax.swing.JTextField jTextParatha;
    private javax.swing.JTextField jTextPizza;
    private javax.swing.JTextArea jTextReceipt;
    private javax.swing.JTextField jTextSnacks;
    private javax.swing.JTextField jTextSubTotal;
    private javax.swing.JTextField jTextTax;
    private javax.swing.JTextField jTextTotal;
    private javax.swing.JTextField jTextTotalCost;
    private javax.swing.JTextField jTextVanilla;
    private javax.swing.JTextField jTextVegBurger;
    private javax.swing.JLabel jTotal;
    private javax.swing.JLabel jTotal1;
    private javax.swing.JLabel jTotal10;
    private javax.swing.JLabel jTotal11;
    private javax.swing.JLabel jTotal2;
    private javax.swing.JLabel jTotal3;
    private javax.swing.JLabel jTotal4;
    private javax.swing.JLabel jTotal5;
    private javax.swing.JLabel jTotal6;
    private javax.swing.JLabel jTotal7;
    private javax.swing.JLabel jTotal8;
    private javax.swing.JLabel jTotal9;
    // End of variables declaration//GEN-END:variables
}
